-- PROVINCIAS DE ESPAÑA
INSERT INTO province (name)
VALUES
	('Albacete'),
	('Alicante'),
	('Almería'),
	('Álava'),
	('Asturias'),
	('Ávila'),
	('Badajoz'),
	('Islas Baleares'),
	('Barcelona'),
	('Bizkaia'),
	('Burgos'),
	('Cáceres'),
	('Cádiz'),
	('Cantabria'),
	('Castellón'),
	('Ceuta'),
	('Ciudad Real'),
	('Córdoba'),
	('La Coruña'),
	('Cuenca'),
	('Gipuzkoa'),
	('Girona'),
	('Granada'),
	('Guadalajara'),
	('Huelva'),
	('Huesca'),
	('Jaén'),
	('León'),
	('Lugo'),
	('Lleida'),
	('Madrid'),
	('Málaga'),
	('Melilla'),
	('Murcia'),
	('Navarra'),
	('Ourense'),
	('Palencia'),
	('Las Palmas'),
	('Pontevedra'),
	('La Rioja'),
	('Salamanca'),
	('Santa Cruz de Tenerife'),
	('Segovia'),
	('Sevilla'),
	('Soria'),
	('Tarragona'),
	('Teruel'),
	('Toledo'),
	('Valencia'),
	('Valladolid'),
	('Zamora'),
	('Zaragoza');
	
-- ROLES
INSERT INTO role (name) VALUES ('usuario'), ('asociacion');